### ISSUE TITLE
ios 7

### ISSUE THREAD

**Issue by binidini** [binidini/tytymyty-ios#16]
можем ли мы поддерживать ios7

25% используют ios 7  если есть возможность дешево и быстро поддержать 7, то надо сделать

**Comment by allnimator** [comment]
Цифры взяты с потолка.
https://developer.apple.com/support/app-store/
менее 10 процентов используют версии раннее 8й.
https://david-smith.org/iosversionstats/
10 процентов используют версии айфона менее 5й.

Предлагаю здесь только скомпилировать и запустить на айос <8. Будут проблемы - забить. Так же с версией айфона. Если падает верстка, то забить. Если проблемы с перекрыванием экрана клавиатурой - пофиксить.

**Comment by allnimator** [comment]
Здесь без тестирования, тк больше не поставляются эмуляторы с 7м ios
