### ISSUE TITLE
поиск

### ISSUE THREAD

**Issue by binidini** [binidini/tytymyty-ios#17]
проверил поиск на iphone

1. иногда пропадает поле ввода -- я не вижу что ввожу - вижу только список подсказок
2. подсказки кривые - нужно, как на сайте 
3. нельзя ввести номер дома, задаю улицу - выбираю из списка и идет поиск --- нет возможности ввести номер дома  - на сайте пример того как надо

**Comment by allnimator** [comment]
Подсказки такие какие есть. Подсказки на сайте используют другие данные, а не те что дает геокодер.

**Comment by allnimator** [comment]
Можно, конечно, использовать адрес для подсказок как на сайте. https://suggest-maps.yandex.ru/suggest-geo?&v=5&search_type=tp&part=%D0%B6%D0%B5%D0%BB%D0%B5%D0%B7%D0%BD%D1%8F%D0%BA%D0%B0&lang=ru_RU&n=5&origin=jsapi2Geocoder&bbox=-180%2C-90%2C180%2C90
Но там в ответ джаваскрипт-код, который надо заебаться парсить. Еще можно поискать другие геокодеры.
