### ISSUE TITLE
нужен процесс  тестирования версии программы

### ISSUE THREAD

**Issue by binidini** [binidini/tytymyty-ios#18]
опиши в вики, как я или кто-нибудь еще могут протестировать новую версию приложения

ждать каждый раз релиза, чтобы начать тестирование - не айс

**Comment by allnimator** [comment]
https://github.com/binidini/tytymyty-ios/wiki/%D0%A2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F
