### ISSUE TITLE
обновление на пуш сообщение

### ISSUE THREAD

**Issue by binidini** [binidini/tytymyty-ios#21]
если пришел пуш

и у нас активно окно с деталями данного заказа - его надо обновить

тоже под андройд

**Comment by allnimator** [comment]
Его там далеко не всегда можно обновить, тк пуш-сообщения в айос - это штука работающая отдельно от приложения.
Тут сложная задача. Ее надо на много частей побить. 1 - переделать на эпловский сервер. 2 -есть кэлбэк на 8й айос, но не знаю можно ли обновить уи при приходе пуш-сообщения.
